package behavior_template_method_pattern;

public class Program {

   public static void main(String[] args) {
      ManagerWorkday managerDay = new ManagerWorkday();
      managerDay.createWorkdayPlan();

      System.out.println();

      PoliceOfficerWorkday policeOfficerDay = new PoliceOfficerWorkday();
      policeOfficerDay.createWorkdayPlan();

   }

}

// Output Console
//Morgentoilette...
//Frühstück...
//Meetings abhalten...
//Abendessen...
//Freizeit-Aktivitäten...
//
//Morgentoilette...
//Frühstück...
//Abendessen...
//Freizeit-Aktivitäten...
